services:
  frontend:
    image: my-vue-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_APP_API_BASE_URL: http://backend:4000
    depends_on:
      - backend

  backend:
    image: my-nestjs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      JWT_SECRET: your_jwt_secret
      JWT_EXPIRATION_TIME: 60m
      DATABASE_URL: mysql://root:admin@database:3306/prueba_db
    depends_on:
      - database

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prueba_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db_data: